### ISSUE TITLE
CPU percentage seems to be aggregated rather than current percentage

### ISSUE THREAD

**Issue by qikaigu** [tmux-plugins/tmux-cpu#19]
I found that the CPU percentage for Linux seems to be the average CPU percentage since boot. As a result, it can hardly reflect current percentage if the machine has been up for long time.

**Comment by ctjhoa** [comment]
As mentionned in the README, you must used iostat or sar to get accurate result.
https://github.com/tmux-plugins/tmux-cpu#optional-requirement-linux-bsd-osx

**Comment by qikaigu** [comment]
I don't know what has been changed but I can't reproduce the inaccuracy with `ps` when `iostat` and `sar` are not available. I'll close the issue.
