### ISSUE TITLE
Showing the value of cpu only when I source the file ~/.tmux.conf(Press <c-b> r)

### ISSUE THREAD

**Issue by andreyvpng** [tmux-plugins/tmux-cpu#23]
How i can solve this problem?

[My screen cast](https://asciinema.org/a/vEEq0zwTLmCu9FTmnx4Auhnmu)
[My ~/.tmux.conf](https://github.com/andreyvpng/dotfiles/blob/master/tmux/.tmux.conf)

**Comment by ctjhoa** [comment]
You need to move `run '~/.tmux/plugins/tpm/tpm'` at the end of your `.tmux.conf`.
As you customize the status bar tpm needs to be executed after that.

**Comment by andreyvpng** [comment]
Sorry for stupid question. Thanks for help
