### ISSUE TITLE
Use cuda-smi or any alternative for OSX

### ISSUE THREAD

**Issue by kleinjm** [tmux-plugins/tmux-cpu#24]
This is a feature request to use [cuda-smi](https://github.com/phvu/cuda-smi) to get GPU stats on OSX. Or any other tool for OSX. Thanks!

**Comment by ctjhoa** [comment]
I don't have any Mac so I will not be able to work on that but if someone do a PR I'll be happy to merge it.

**Comment by casperdcl** [comment]
same here, I implemented the `nvidia-smi` version (#22) but don't have a mac.

**Comment by casperdcl** [comment]
AFAIK `cuda-smi` only supports memory percentage, not load: https://github.com/phvu/cuda-smi

doesn't look promising: https://devtalk.nvidia.com/default/topic/839954/command-line-gpu-load-display-on-os-x/
