### ISSUE TITLE
Additional spaces added to symbol and percentage

### ISSUE THREAD

**Issue by cujomalainey** [tmux-plugins/tmux-cpu#25]
Right now I have a config defined as:

`CPU: #{cpu_icon}#{cpu_percentage}`

which is generating

`CPU: =  1.8%` 

There are two spaces between the symbol and the percentage that are being added by the plugin (Markdown appears to be removing one of the additional spaces). In theory the plugin should be stripping its output and letting the end config define its own padding.

**Comment by casperdcl** [comment]
looking at https://github.com/tmux-plugins/tmux-cpu/blob/12f7a74e25bf59701456e2c0d98b39bb19ec7039/scripts/cpu_percentage.sh#L28 the format is currently `5.2f%`

**Comment by cujomalainey** [comment]
That would explain the padding, probably should be adjusted
