### ISSUE TITLE
what does the cpu icon do?

### ISSUE THREAD

**Issue by isthisthat** [tmux-plugins/tmux-cpu#3]
Hello,
What is `#{cpu_icon}` intended for? Does it change shape/color when CPU is loaded for example? Or is it just decorative?
Thanks.

**Comment by ctjhoa** [comment]
Hi,
Just decorative for the moment.
An icon based on the cpu load is feasible I think but as I don't have MacOS I cannot guarantee the result in this OS.
If I got some time I will try to do that for fun.

**Comment by ctjhoa** [comment]
Since ed2f1590b603b2dffcfcf1d5d1c73054df802542 this plugin supports dynamic icon depending on the cpu percentage.
