### ISSUE TITLE
Add option to zero-prefix cpu frequency

### ISSUE THREAD

**Issue by twilco** [tmux-plugins/tmux-cpu#30]
Thanks for this awesome plugin!  One idea - it would be neat if you could prefix single digit CPU usage percentages with a zero - e.g. `05%`.  Currently, when my computer hovers between single-digit and double-digit percentage usages (e.g. 9% to 10%), the width of the status bar changes constantly, which is slightly distracting.  Prefixing single-digit percentage usages with a zero would prevent this.

**Comment by casperdcl** [comment]
I sort of expected someone to complain after fixing #25 :)

I have no strong preference.

**Comment by twilco** [comment]
Ah, I actually agree with the point made in that issue.  For anyone who wants this functionality, here's a janky little inline script I used:

```
set -g status-right '#{prefix_highlight}  #{badge_docker} | #{cpu_icon} #(cpu_perc="#{cpu_percentage}"; if [ $( echo "$cpu_perc" | wc -m | xargs ) -le 5 ]; then echo "0$cpu_perc"; else echo "$cpu_perc"; fi) | %I:%M %p '
```
