### ISSUE TITLE
Option to hide CPU % when less than a minimum value

### ISSUE THREAD

**Issue by dpacbach** [tmux-plugins/tmux-cpu#31]
Can you add an option to specify a "minimum" CPU percentage below which the CPU percentage variable will just be blank?  As it is right now, when my terminal is sitting idle, the CPU percentage is fluctuating around 3-10% which I am not really interested in seeing; it's really only interesting when the CPU is in use.  Thanks

**Comment by ctjhoa** [comment]
I don't think that it should be an new option as it's very specific.
However you could easily fork this repo and modify
https://github.com/tmux-plugins/tmux-cpu/blob/master/scripts/cpu_percentage.sh

Then you could install your fork like this `set -g @plugin 'dpacbach/tmux-sensible'`
