### ISSUE TITLE
Left side words of cpu percentage are not aligned

### ISSUE THREAD

**Issue by narugit** [tmux-plugins/tmux-cpu#32]
# Problem 
Like below figure, the left side words of cpu percentage are not aligned when cpu percentage's number of digits changes.

<img width="348" alt="not-align" src="https://user-images.githubusercontent.com/28133383/62206046-dda7b780-b3cb-11e9-8c4f-01121a0469a6.png">
Figure: Not aligned left words of cpu percentage

# Desired Appearance
I want to align the left side words of cpu percentage not depending on cpu percentage's number of digits.

**Comment by ctjhoa** [comment]
This was formerly the plugin behavior.
However, it has been reverted on purpose with https://github.com/tmux-plugins/tmux-cpu/pull/29
For more flexibilty, we can introduce a new variable which could enable padding.

**Comment by narugit** [comment]
Thank you for quick reply.
I see. I'm sorry for missing it.  
> For more flexibilty, we can introduce a new variable which could enable padding.

Sounds great. How about introduce `#{cpu_percentage_with_right_justified}` which is my desired one or better idea?

**Comment by ctjhoa** [comment]
Sorry for the delay, I have finally introduce a new option to customize the percentage format.
0e6fb34a3ec499c6239e8bb3c4867e3449588a09

Upgrading this plugin and using:
```shell
set -g @cpu_percentage_format "%5.1f%%" # Add left padding
```
should solve the issue.
