### ISSUE TITLE
RAM percentage doesn't work 

### ISSUE THREAD

**Issue by Ronll** [tmux-plugins/tmux-cpu#44]
I am using ubuntu 19.10 on a dell xps 13 9370 

.tmux.config:
> set -g status-right 'CPU: #{cpu_percentage} | MEM: #{ram_percentage}| Battery: #{battery_percentage} | %H:%M '

Actual result: 
![image](https://user-images.githubusercontent.com/12170856/77627257-4b05eb00-6f4f-11ea-8e20-60130af789cf.png)
(ram percentage is missing)

Didn't see anything in the "tmux-client-*.log" logs, let me know if I can share any other useful info

**Comment by casperdcl** [comment]
Can you clone the repository and run `scripts/ram_percentage.sh`? There should be an output percentage...

**Comment by Ronll** [comment]
Seems to work

![image](https://user-images.githubusercontent.com/12170856/77862214-a1f71300-7222-11ea-98c3-b3df900d0e5f.png)

**Comment by casperdcl** [comment]
Right so that means you need to update/reload your `tmux` env.

`prefix + U(uppercase)`, `all`, `[Enter]`

**Comment by Ronll** [comment]
Worked like a charm, 

Thanks.

**Comment by vinipsmaker** [comment]
It doesn't work here. I debugged the problem and the fix is to just put this at the beginning of the file `scripts/ram_percentage.sh`:

```
export LANG=C
```

**Comment by casperdcl** [comment]
@vinipsmaker feel like opening a PR?
