### ISSUE TITLE
Incorrect format for cpu

### ISSUE THREAD

**Issue by Rizhiy** [tmux-plugins/tmux-cpu#59]
Hi, I recently updated and CPU percentage is in the wrong format:

- Comma (,) is used as a decimal separator instead of a period (.)
- Colors are being assinged incorrectly, e.g. 9% is being treated as 90%.

**Comment by Rizhiy** [comment]
![image](https://user-images.githubusercontent.com/5617397/94968386-79214480-0509-11eb-8dcf-8b8cbc490f8d.png)

**Comment by casperdcl** [comment]
Hmm I wonder if this is related to #44. Could you try the [`fix-lang` branch](https://github.com/tmux-plugins/tmux-cpu/tree/fix-lang)?

**Comment by Rizhiy** [comment]
It might be, I believe my system uses Russian format which does indeed use comma as a decimal separator.

**Comment by casperdcl** [comment]
you should be able to `~/.tmux/plugins/tmux-cpu && git pull && git checkout fix-lang` to try this out

**Comment by Rizhiy** [comment]
`fix-lang` fixed it for me.
