### ISSUE TITLE
Incorrect memory usage display

### ISSUE THREAD

**Issue by maxless** [tmux-plugins/tmux-cpu#62]
Sometimes I can see memory usage like this:
![image](https://user-images.githubusercontent.com/6419589/98109184-9786b100-1eb6-11eb-9250-f4205ba290fd.png)
It stays like this for a short period of time (probably the update period) and then shows correctly:
![image](https://user-images.githubusercontent.com/6419589/98109294-c1d86e80-1eb6-11eb-9a40-df60c13cec5e.png)
That leads me to another issue - you can see how MEM is green, is there a way to reset the text color back to default?

I use Ubuntu 20.04 on WSL2. Tmux version is 3.0a. The relevant config section is:
```
set-option -g status-left-length 20
set-option -g status-left "#S | "
set-option -g status-left-style fg=#aaaaaa,bg=#050505
set-option -g status-style fg=#aaaaaa,bg=#050505
set-option -g status-right 'CPU: #{cpu_fg_color}#{cpu_percentage} MEM: #{ram_fg_color}#{ram_percentage}'
set-option -g status-right-style fg=#aaaaaa,bg=#050505
```

**Comment by casperdcl** [comment]
reset colours:

```diff
-set-option -g status-right 'CPU: #{cpu_fg_color}#{cpu_percentage} MEM: #{ram_fg_color}#{ram_percentage}'
+set-option -g status-right 'CPU: #{cpu_fg_color}#{cpu_percentage}#[fg=#aaaaaa] MEM: #{ram_fg_color}#{ram_percentage}'
```

**Comment by maxless** [comment]
Thanks for the colors bit.

This is is first time I'm using this plugin so I don't know whether it's related to Ubuntu version.

**Comment by casperdcl** [comment]
> 20.04 on WSL2. Tmux version is 3.0a

Sounds like life on the edge

**Comment by maxless** [comment]
Nah, I just got to upgrading my periodical development environment (happens around every 2 years) and it coincided with the WSL2 release :)

I've noticed some shell scripts in htop running periodically, if they're from tmux-cpu, perhaps I could give you their input/output for debugging?

**Comment by casperdcl** [comment]
I guess the problem is [this](https://github.com/tmux-plugins/tmux-cpu/blob/9eb3dba66672c5b43065e144cc3a1031f77ad67e/scripts/helpers.sh#L110-L150) is not atomic
