### ISSUE TITLE
Default `cpu_temp_fg_color` is actually bg color. Typo?

### ISSUE THREAD

**Issue by AllanChain** [tmux-plugins/tmux-cpu#63]
https://github.com/tmux-plugins/tmux-cpu/blob/72289570d098e2549ca585eb731494e89f801ae3/scripts/cpu_temp_fg_color.sh#L11-L13

And GPU too

https://github.com/tmux-plugins/tmux-cpu/blob/72289570d098e2549ca585eb731494e89f801ae3/scripts/gpu_temp_fg_color.sh#L11-L13

**Comment by casperdcl** [comment]
Ah also applies to `gpu_temp_*`
