### ISSUE TITLE
Ram doesn't properly colorize.

### ISSUE THREAD

**Issue by wojciechGaudnik** [tmux-plugins/tmux-cpu#70]
![image](https://user-images.githubusercontent.com/32289094/137959910-1eb01585-c9ec-4e06-9288-283cd73bdfe8.png)

I need some help, what I made wrong?
CPU usage and CPU temp are colorized properly. 
I mean RAM is still yellow.

**Comment by ctjhoa** [comment]
@wojciechGaudnik this should be fixed now
